export const PDUFA_DATA = [
  {
    id: "1",
    company: "Ascendis Pharma A/S",
    ticker: "ASND",
    drug: "TransCon CNP",
    treatment: "Achondroplasia",
    pdufaDate: "2026-02-28",
    approvalType: "BLA",
    priority: "Standard",
    status: "Pending",
    description: "For treatment of children with achondroplasia"
  },
  {
    id: "2",
    company: "BioMarin Pharmaceutical Inc",
    ticker: "BMRN",
    drug: "PALYNZIQ",
    treatment: "Phenylketonuria",
    pdufaDate: "2026-02-28",
    approvalType: "BLA",
    priority: "Priority",
    status: "Pending",
    description: "For treatment in adolescents with phenylketonuria (PKU)"
  },
  {
    id: "3",
    company: "Eton Pharmaceuticals Inc",
    ticker: "ETON",
    drug: "ET-600",
    treatment: "Central Diabetes Insipidus",
    pdufaDate: "2026-02-25",
    approvalType: "NDA",
    priority: "Standard",
    status: "Pending",
    description: "Desmopressin oral solution for treatment of central diabetes insipidus"
  },
  {
    id: "4",
    company: "Vanda Pharmaceuticals Inc",
    ticker: "VNDA",
    drug: "Bysanti",
    treatment: "Bipolar I Disorder",
    pdufaDate: "2026-02-21",
    approvalType: "NDA",
    priority: "Standard",
    status: "Review",
    description: "For treatment of acute bipolar I disorder and schizophrenia"
  },
  {
    id: "5",
    company: "Vertex Pharmaceuticals",
    ticker: "VRTX",
    drug: "VX-548",
    treatment: "Pain Management",
    pdufaDate: "2026-02-22",
    approvalType: "NDA",
    priority: "Priority",
    status: "Review",
    description: "Non-opioid acute pain treatment (NaV1.8 inhibitor)"
  },
  {
    id: "6",
    company: "Pfizer Inc",
    ticker: "PFE",
    drug: "Hympavzi",
    treatment: "Hemophilia B",
    pdufaDate: "2026-03-15",
    approvalType: "BLA",
    priority: "Priority",
    status: "Pending",
    description: "Gene therapy for hemophilia B (marstacimab)"
  },
  {
    id: "7",
    company: "Bristol Myers Squibb",
    ticker: "BMY",
    drug: "Opdivo",
    treatment: "Hodgkin Lymphoma",
    pdufaDate: "2026-04-08",
    approvalType: "BLA",
    priority: "Priority",
    status: "Pending",
    description: "Supplemental Biologics License Application (sBLA)"
  },
  {
    id: "8",
    company: "Moderna Inc",
    ticker: "MRNA",
    drug: "mRNA-4157",
    treatment: "Oncology",
    pdufaDate: "2026-03-02",
    approvalType: "BLA",
    priority: "Accelerated",
    status: "Pending",
    description: "Individualized cancer vaccine in combination with pembrolizumab"
  },
  {
    id: "9",
    company: "Merck & Co",
    ticker: "MRK",
    drug: "modakafusp alfa",
    treatment: "Multiple Myeloma",
    pdufaDate: "2026-03-05",
    approvalType: "BLA",
    priority: "Priority",
    status: "Pending",
    description: "TGF-β trap for relapsed/refractory multiple myeloma"
  },
  {
    id: "10",
    company: "AstraZeneca",
    ticker: "AZN",
    drug: "danicopan",
    treatment: "PNH",
    pdufaDate: "2026-03-08",
    approvalType: "NDA",
    priority: "Standard",
    status: "Pending",
    description: "Oral Factor D inhibitor for paroxysmal nocturnal hemoglobinuria"
  }
];
